# permissions for end users to edit does.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: do-editor-role
rules:
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - does
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - does/status
  verbs:
  - get
