# permissions for end users to view does.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: do-viewer-role
rules:
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - does
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - does/status
  verbs:
  - get
