# permissions for end users to edit dots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dot-editor-role
rules:
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - dots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - dots/status
  verbs:
  - get
