# permissions for end users to view scales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scale-viewer-role
rules:
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - scales
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.adityajoshi.online
  resources:
  - scales/status
  verbs:
  - get
